<h2>mon parcours</h2>
<div class="career">
<!-- FIRST -->
	<div class="event left first">
		<div class="top">
			<div class="title"><h3>3W Academy</h3></div>
			<div class="square blue"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line blue"></div>
			<div class="circle blue"></div>
			<div class="date blue">2016</div>
		</div>
		<div class="body">
			<p>Formation Développeur Intégrateur Web :</p>
			<ul>
				<li>HTML</li>
				<li>CSS</li>
				<li>Javascript</li>
				<li>PhP</li>
			</ul>
		</div>
	</div>
<!-- SECOND -->
	<div class="event right second">
		<div class="top">
			<div class="title"><h3>Timken Company</h3></div>
			<div class="square"><p><i class="fa fa-cogs"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2015 - 2016</div>
		</div>
		<div class="body">
			<p>Préparateur de commandes</p>
		</div>
	</div>
<!-- THIRD -->
	<div class="event left third">
		<div class="top">
			<div class="title"><h3>ISLT</h3></div>
			<div class="square"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2014</div>
		</div>
		<div class="body">
			<p>VAE (validation des acquis de l'expérience) </p>
			<p>Technicien en logistique d'entreposage</p>
		</div>
	</div>
<!-- FOURTH -->
	<div class="event right fourth">
		<div class="top">
			<div class="title"><h3>Sermes Distribution</h3></div>
			<div class="square"><p><i class="fa fa-truck"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2010-2013</div>
		</div>
		<div class="body">
			<p>Gestionnaire de stock</p>
			<p>Magasinier cariste</p>
		</div>
	</div>
<!-- FIFTH -->
	<div class="event left fifth">
		<div class="top">
			<div class="title"><h3>ECF Llerena</h3></div>
			<div class="square"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2010</div>
		</div>
		<div class="body">
			<p>Professionnalisation Magasier cariste</p>
			<p>CACES 1-3-5</p>
		</div>
	</div>
<!-- SIXTH -->
	<div class="event right sixth">
		<div class="top">
			<div class="title"><h3>MTD</h3></div>
			<div class="square"><p><i class="fa fa-briefcase"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2008-2009</div>
		</div>
		<div class="body">
			<p>Agent de montage</p>
		</div>
	</div>
<!-- SEVENTH -->
	<div class="event left seventh">
		<div class="top">
			<div class="title"><h3>Johnson Controls</h3></div>
			<div class="square"><p><i class="fa fa-battery-full"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2007-2008</div>
		</div>
		<div class="body">
			<p>Contrôleur qualité</p>
		</div>
	</div>
<!-- EIGHTH -->
	<div class="event right eighth">
		<div class="top">
			<div class="title"><h3>Albert Schweitzer</h3></div>
			<div class="square"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue">2005-2006</div>
		</div>
		<div class="body">
			<p>BEP Electrotechnique</p>
		</div>
	</div>
</div>