<h2>mon parcours</h2>
<div class="career">
<!-- FIRST -->
	<div class="event left first">
		<div class="top">
			<div class="title"><h5>3W Academy</h5></div>
			<div class="square blue"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line blue"></div>
			<div class="circle blue"></div>
			<div class="date blue"><p>2016</p></div>
		</div>
		<div class="body">
			<p>Formation Développeur Intégrateur Web :</p>
			<ul>
				<li>HTML</li>
				<li>CSS</li>
				<li>Javascript</li>
				<li>PhP</li>
			</ul>
		</div>
	</div>
<!-- SECOND -->
	<div class="event right second">
		<div class="top">
			<div class="title"><h5>Timken Company</h5></div>
			<div class="square"><p><i class="fa fa-cogs"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2015 - 2016</p></div>
		</div>
		<div class="body">
			<p>Préparateur de commandes</p>
		</div>
	</div>
<!-- THIRD -->
	<div class="event left third">
		<div class="top">
			<div class="title"><h5>ISLT</h5></div>
			<div class="square"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2014</p></div>
		</div>
		<div class="body">
			<p>VAE (validation des acquis de l'expérience)<br>Technicien en logistique d'entreposage</p>
		</div>
	</div>
<!-- FOURTH -->
	<div class="event right fourth">
		<div class="top">
			<div class="title"><h5>Sermes Distribution</h5></div>
			<div class="square"><p><i class="fa fa-truck"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2010 - 2013</p></div>
		</div>
		<div class="body">
			<p>Gestionnaire de stock<br>Magasinier cariste</p>
		</div>
	</div>
<!-- FIFTH -->
	<div class="event left fifth">
		<div class="top">
			<div class="title"><h5>ECF Llerena</h5></div>
			<div class="square"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2010</p></div>
		</div>
		<div class="body">
			<p>Professionnalisation Magasier cariste</p>
			<p>CACES 1-3-5</p>
		</div>
	</div>
<!-- SIXTH -->
	<div class="event right sixth">
		<div class="top">
			<div class="title"><h5>MTD</h5></div>
			<div class="square"><p><i class="fa fa-briefcase"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2008 - 2009</p></div>
		</div>
		<div class="body">
			<p>Agent de montage</p>
		</div>
	</div>
<!-- SEVENTH -->
	<div class="event left seventh">
		<div class="top">
			<div class="title"><h5>Johnson Controls</h5></div>
			<div class="square"><p><i class="fa fa-battery-full"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2007-2008</p></div>
		</div>
		<div class="body">
			<p>Contrôleur qualité</p>
		</div>
	</div>
<!-- EIGHTH -->
	<div class="event right eighth">
		<div class="top">
			<div class="title"><h5>Lycée Albert Schweitzer</h5></div>
			<div class="square"><p><i class="fa fa-graduation-cap"></i></p></div>
			<div class="line"></div>
			<div class="circle"></div>
			<div class="date blue"><p>2005 - 2006</p></div>
		</div>
		<div class="body">
			<p>BEP Electrotechnique</p>
		</div>
	</div>
</div>