<div class="content_pages">

	<div class="title title-fco">
		<h2><span class="bold">Projet</span> fc Ostwald</h2>
		<img src="assets/images/fco/screen.png" alt="">
	</div>

	<div class="description description-fco">
		<h3>Description</h3>
		<p>Le projet Fc Ostwald à été lancé lorsque je dirigais l'équipe U18 (section jeune regroupant les 15, 16 et 17 ans). Je ne connaissait rien aux langages web mais grâce à Photoshop et (oh sacrilège !) Dreamweaver le site de l'équipe a put voir le jour.</p>
	</div>

	<div class="context">
		<div class="block-fco">
	 		<img src="assets/images/fco/inclin.png" alt="">
	 		<div class="fco-text">
	 			<h3>Contexte</h3>
	 			<p>Résumés des matches en passant par les compositions d’équipe ainsi que des statistiques concernant tout l’effectif, ce site déstiné à ameliorer la communication du groupe s’est vite rendu indispensable.</p>
	 		</div>
		</div>

		<div class="block-fco">
				<div class="fco-text">
					<h3>Refonte du logo du club</h3>
					<p>Au bout de plusieurs essais, je pense avoir trouvé quelque chose...</p>
				</div>
			<div class="before-after">
				<div class="before">
					<h3 class="before-date">2014</h3>
					<img src="assets/images/fco/before.png" alt="">
				</div>
				<div class="after">
					<h3 class="before-date">2016</h3>
					<img src="assets/images/fco/after.png" alt="">
				</div>
			</div>
		</div>

		<div class="block-fco">
			<img src="assets/images/fco/deck.png" alt="">
			<div class="fco-text">
	 			<h3>Player's Cards</h3>
	 			<p>Chaque joueur a eu droit à une carte personnalisée, un petit clin d'oeil à l'heure ou ils passaient le plus clair de leurs temps libre sur un célèbre jeu de football.</p>
	 		</div>
		</div>
	</div>

	<div class="lightbox" id="lightbox">
		<h3>Photos souvenirs</h3>
			<img id="zoom1" class="isFade" src="assets/images/pics/teamblue.jpg">
			<img id="zoom2" class="isFade" src="assets/images/pics/teamgreen.jpg">
			<img id="zoom3" class="isFade" src="assets/images/pics/win.jpg">
<!-- 		<div id="show" class="white_content isShowing" >
		</div> -->
		<img id="polaroid1" class="polaroid1" src="assets/images/pics/teamblue.png">
		<img id="polaroid2" class="polaroid2" src="assets/images/pics/teamgreen.png">
		<img id="polaroid3" class="polaroid3" src="assets/images/pics/win.png">
	<!-- 	
		<a href="javascript:void(0)" onclick="document.getElementById('light1').style.display='inline-block';document.getElementById('fade').style.display='inline-block'"><img src="assets/images/pics/teamgreen.png"></a>
		<a href="javascript:void(0)" onclick="document.getElementById('light2').style.display='inline-block';document.getElementById('fade').style.display='inline-block'"><img class="pic2" src="assets/images/pics/win.png"></a> -->
		

<!-- 		<div id="light1" class="isFade white_content" onclick="document.getElementById('light1').style.display='none';document.getElementById('fade').style.display='none'">
			<img src="assets/images/pics/teamgreen.jpg">
			<a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='none';document.getElementById('fade').style.display='none'"></a>
		</div>

		<div id="light2" class="isFade white_content" onclick="document.getElementById('light2').style.display='none';document.getElementById('fade').style.display='none'">
			<img src="assets/images/pics/win.jpg">
			<a href = "javascript:void(0)" onclick="document.getElementById('light2').style.display='none';document.getElementById('fade').style.display='none'"></a>
		</div>
		 -->
		<div id="fade" class="black-overlay isFade"></div>
	</div>

</div>