<h2>PORTFOLIO</h2>
<div class="portfolio">
	<div class="hover" id="hover_web">
		<h2>RÉALISATIONS WEB</h2>
		<p>Je partage dans cette rubrique les réalisations WEB les plus récentes, ainsi que celles dont je suis le plus fier.</p>
		<img src="assets/images/screen.png">
	</div>
	<div class="hover" id="hover_design">
		<h2>GRAPH & DESIGN</h2>
		<p>Voici quelques réalisations que j'ai pris plaisir a réaliser et que je partage aujour'hui avec vous.</p>
		<img src="assets/images/screen.png">
	</div>
</div>