<div class="creations">
	<div id="creation-1">
		<h3>Sweethome</h3>
		<a href="index.php?page=sweethome"><img src="./assets/images/sweethome/tablet_home.png"></a>
	</div>
	<div id="creation-2">
		<h3>Football Club Ostwald</h3>
		<a href="index.php?page=fcostwald"><img src="./assets/images/fco/fco_home.png"></a>
	</div>
	<div id="creation-3">
		<h3>Football Club FCSK</h3>
		<a href="#"><img src="./assets/images/fcsk/fcsk06_home.png"></a>
	</div>
</div>