<h2>mon portfolio</h2>
<div class="creations">
	<div class="txtIntro">
		<p>J'ai réalisé ce Portfolio dans le cadre de la validation de ma formation de "Développeur Intégrateur Web" à la 3W Academy. Voici un aperçu de quelques unes de mes réalisations, j'espère que vous les apprécierais. </p>
	</div>
	<div id="creation-1">
		<h4>Sweethome</h4>
		<a href="sweethome"><img src="./assets/images/sweethome/tablet_home.png" alt=""></a>
	</div>
	<div id="creation-2">
		<h4>Football Club Ostwald</h4>
		<a href="fcostwald"><img src="./assets/images/fco/fco_home.png" alt=""></a>
	</div>
	<div id="creation-3">
		<h4>Football Club FCSK</h4>
		<a href="#"><img src="./assets/images/fcsk/fcsk06_home.png" alt=""></a>
	</div>
</div>