<div class="sidebar" id="sidebar">
	<div class="menu" id="menu">
		<div class="line" id="top"></div>
		<div class="line" id="mid"></div>
		<div class="line" id="bot"></div>
	</div>
	<div class="ics" id="ics">
		<div class="ics-r" id="ics-r"></div>
		<div class="ics-l" id="ics-l"></div>
	</div>
	<!-- <div class="c-hamburger c-hamburger--htx"><span></span></div> -->
	<div class="links show-links" id="links">
		<p><a href="home">home</a></p>
		<p><a href="portfolio">portfolio</a></p>
		<p><a href="career">mon parcours</a></p>
		<p><a href="contact">contact</a></p>
	</div>
	<div class="back-transparent"></div>
</div>