<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="assets/styles/style.css">
        <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
        <meta charset="UTF-8">
        <title>Portfolio - <?= $page?></title>
    </head>

	<body>
        <div class="content">
            <?php require("controller/content.php"); ?>
            <?php require("controller/sidebar.php"); ?>
        </div>
        <script type="text/javascript" src="./assets/scripts/script.js"></script>
	</body>
</html>