<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, height=device-height, maximum-scale=1, initial-scale=1, user-scalable=no">
        <title>Portfolio - <?= $page?></title>
        <meta name="robots" content="index, follow">
        <meta name="description" content="Portoflio 3W Academy Hank Faress" />
        <meta name="keywords" content="portfolio, développeur, intégrateur, web, developper" />
        <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
        <link rel="icon" type="image/x-icon" href="./favicon.ico"  />
        <link rel="stylesheet" type="text/css" href="bower_components/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="assets/styles/style.css">
    </head>

	<body>
        <div class="content">
            <?php require("controller/".$page.".php"); ?>
            <?php require("controller/sidebar.php"); ?>
        </div>
        <script type="text/javascript" src="assets/scripts/script.js"></script>
	</body>
</html>