<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, height=device-height, maximum-scale=1, initial-scale=1, user-scalable=no">
        <title>Portfolio - <?= $page?></title>
        <link rel="stylesheet" href="assets/bower_components/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="assets/styles/style.css">
    </head>

	<body>
        <div class="content">
            <?php require("controller/".$page.".php"); ?>
            <?php require("controller/sidebar.php"); ?>
        </div>
        <script type="text/javascript" src="assets/scripts/script.js"></script>
	</body>
</html>