<div class="content_pages">

	<div class="title">
		<h2><span class="bold">Projet</span> sweethome</h2>
		<img src="./assets/images/sweethome/tablet.png" alt="">
		<div class="price"><h2><i class="fa fa-trophy cup"></i> Lauréat du prix Scalingo au Hacking Industry Camp 2016 <i class="fa fa-trophy cup"></i></h2></div>
	</div>

	<div class="description">
		<h3>Description</h3>
		<p>Sweethome vise à fournir aux particuliers, grâce aux plans de leurs habitations, une interface érgonomique pour la gestion de leur domotique. Ce projet a été réalisé lors du Hacking Industry Camp 2016 à Strasbourg.</p>
		<br>
		<p>Ce Hackhaton s'est déroulé le week-end du 14 au 16 octobre 2016, durant 54h nous avons développé l'application SWEETHOME qui a remporté le prix Scalingo.</p>
	</div>

	<div class="context">
		<div class="context-block">
			<div class="context-side align-left">
				<h3>Contexte</h3>
				<p>Chargé du développement front-end du projet, ma fonction consistait à concevoir la structure de l’application web ainsi que l’intégration des éléments graphiques.</p>
			</div>
			<img src="./assets/images/sweethome/tablet_demo.png" alt="">
			<!-- <img class="sweet-text" src="assets/images/sweethome/sweet_taixt.png" alt=""> -->
		</div>
		<div class="context-block">
			<img class="imgleft" src="./assets/images/sweethome/suitcase.png" alt="">
			<div class="context-side align-right">
			<h3>Fonctionnement</h3>
				<p>L'application connectée à notre superbe valise domotique, permet d'intéragir avec cette dernière. Contrôler  son domicile à distance, n'a jamais été aussi facile.</p>
			</div>
			<!-- <img class="sweet-text" src="assets/images/sweethome/sweet_taixt.png" alt=""> -->
		</div>

<!-- 		<div class="context-block">
			<p>Le défi a été de réaliser, grâce a une équipe motivé, tous les aspects de notre vprojet en moins de 54h.</p>
			<img src="assets/images/sweethome/..." alt="">
		</div>
 -->
		<div class="context-block">
			<div class="context-side align-left">
				<h3>Coulisses</h3>
				<p>La matière grise s'active et les idées fusent. Il faut trancher dans le vif, pas le temps de paufiner tout les détails, le pitch c'est dimanche matin!</p>
			</div>
			<img class="table" src="./assets/images/sweethome/table2.png" alt="">
			<img class="table2" src="./assets/images/sweethome/table.png" alt="">
		</div>
	</div>
	<div class="lightbox">
		<h3>Photos souvenirs</h3>
			<img id="zoom1" class="isFade" src="./assets/images/pics/hicteam.jpg">
			<img id="zoom2" class="isFade" src="./assets/images/pics/hic2016.jpg">
			<img id="zoom3" class="isFade" src="./assets/images/pics/scalingo.jpg">

		<img id="polaroid1" class="polaroid1" src="./assets/images/pics/sweetteam.png">
		<img id="polaroid2" class="polaroid2" src="./assets/images/pics/hic2016.png">
		<img id="polaroid3" class="polaroid3" src="./assets/images/pics/scalingo.png">


		
		<div id="fade" class="black-overlay isFade"></div>
	</div>
		<!-- <div class="demo">
			<div class="tab">
				<img src="./assets/images/sweethome/tablet_on750.png" alt="">
				<div class="screen">
					require('view/test.phtml')
				</div>
			</div>
		</div> -->
</div>